# Generated by Django 2.2.4 on 2020-03-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='user',
        ),
    ]
