# Generated by Django 2.2.4 on 2020-03-19 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_remove_expenditure_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sub_category_link',
        ),
        migrations.AddField(
            model_name='data',
            name='category_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='expense.Expenditure'),
        ),
    ]
